config/routes.rb
Civet::Application.routes.draw do

  # User registration (coded links)
  get  'register/:code' => 'users#new',   as: :register        # Registration form
  post 'register/:code' => 'users#create'                      # Create new user/destroy registrant
  
  get    'login'  => 'session#new',     as: :login             # Login form
  post   'login'  => 'session#create'                          # Log user in (start session)
  delete 'logout' => 'session#destroy', as: :logout            # Log user out (end session)
  
  scope :api do
    
    get '' => 'api#index', as: :api, defaults: { format: :json }
    
    resources :jobs, except: [ :show, :new, :edit ], defaults: { format: :json } do
      get ':id' => 'jobs#index', on: :collection
    end
    
    resources :schools, except: [ :show, :new, :edit ], defaults: { format: :json } do
      get ':id' => 'schools#index', on: :collection
    end
    
    resources :refs, except: [ :show, :new, :edit ], defaults: { format: :json } do
      get ':id' => 'refs#index', on: :collection
    end
  
    resources :vitaes, except: [ :show, :new, :edit ], defaults: { format: :json } do
      get ':id' => 'vitaes#index', on: :collection
      get 'jobs(/:id)' => 'jobs#index', as: :jobs
      get 'schools(/:id)' => 'schools#index', as: :schools
      get 'refs(/:id)' => 'refs#index', as: :refs
    end
  
    get   'profile' => 'user#show',  as: :profile              # User information
    patch 'profile' => 'user#update'                           # Update user
    
  end
  
  # Public CV (coded link)
  get 'cv/:code' => 'vitae#show', as: :cv

  # Password reset (coded links)
  get   'reset/:code' => 'password#edit',  as: :reset          # Password reset form
  patch 'reset/:code' => 'password#update'                     # Reset users password
  
  get 'vitaes'    => 'site#index'
  get 'vitae/:id' => 'site#index'
  
  # Dashboard
  root 'site#index'
end

app/views/notifier/password_reset.html.erb
<p>
  Your Civet credentials have been reset. If you
  did not reset them, please contact us.
</p>

<p>Thanks!<br>Civet</p>

app/views/notifier/password_reset.text.erb
Your Civet credentials have been reset. If you did not reset them, please contact us.

Thanks!
Civet

app/views/notifier/password_reset_request.html.erb
<p>
  We received a request to reset your Civet credentials.
  To do so, please follow the coded link below:
</p>

<p>
  <%= link_to reset_url(@user.code), reset_url(@user.code) %>
</p>

<p>
  If you received this email in error, simply do nothing.
  The above link will expire at <%= @user.expires_at.strftime("%-I:%M on %a, %-d %b %Y") %>
</p>

<p>Thanks!<br>Civet</p>

app/views/notifier/password_reset_request.text.erb
We received a request to reset your Civet credentials. To do so, please follow the coded link below:

<%= link_to reset_url(@user.code), reset_url(@user.code) %>

If you received this email in error, simply do nothing. The above link will expire at <%= @user.expires_at.strftime("%-I:%M on %a, %-d %b %Y") %>.

Thanks!
Civet

app/views/notifier/registration.html.erb
<p>
  Thank you for registering with Civet. If you
  did not register with us, please contact us.
</p>

<p>Thanks!<br>Civet</p>

app/views/notifier/registration.text.erb
Thank you for registering with Civet. If you did not register with us, please contact us.

Cheers!
Civet

app/views/notifier/registration_request.html.erb
<p>
  Thank you for registering with Civet! To complete
  your registration, please follow the link below:
</p>

<p>
  <%= link_to register_url(@registrant.code), register_url(@registrant.code) %>
</p>

<p>
  If you received this email in error, simply do nothing.
  The above link will expire at <%= @registrant.expires_at.strftime("%-I:%M on %a, %-d %b %Y") %>
</p>

<p>Thanks!<br>Civet</p>

app/views/notifier/registration_request.text.erb
Thank you for registering with Civet! To complete your registration, please follow the link below:

<%= link_to register_url(@registrant.code), register_url(@registrant.code) %>

If you received this email in error, simply do nothing. The above link will expire at <%= @registrant.expires_at.strftime("%-I:%M on %a, %-d %b %Y") %>.

Thanks!
Civet