config/routes.rb
Civet::Application.routes.draw do

  # User registration (coded links)
  get  'register/:code' => 'users#new',   as: :register        # Registration form
  post 'register/:code' => 'users#create'                      # Create new user/destroy registrant
  
  get    'login'  => 'session#new',     as: :login             # Login form
  post   'login'  => 'session#create'                          # Log user in (start session)
  delete 'logout' => 'session#destroy', as: :logout            # Log user out (end session)
  
  scope :api do
    
    get '' => 'api#index', as: :api, defaults: { format: :json }
    
    resources :jobs, except: [ :show, :new, :edit ], defaults: { format: :json } do
      get ':id' => 'jobs#index', on: :collection
    end
    
    resources :schools, except: [ :show, :new, :edit ], defaults: { format: :json } do
      get ':id' => 'schools#index', on: :collection
    end
    
    resources :refs, except: [ :show, :new, :edit ], defaults: { format: :json } do
      get ':id' => 'refs#index', on: :collection
    end
  
    resources :vitaes, except: [ :show, :new, :edit ], defaults: { format: :json } do
      get ':id' => 'vitaes#index', on: :collection
      get 'jobs(/:id)' => 'jobs#index', as: :jobs
      get 'schools(/:id)' => 'schools#index', as: :schools
      get 'refs(/:id)' => 'refs#index', as: :refs
    end
  
    get   'profile' => 'user#show',  as: :profile              # User information
    patch 'profile' => 'user#update'                           # Update user
    
  end
  
  # Public CV (coded link)
  get 'cv/:code' => 'vitae#show', as: :cv

  # Password reset (coded links)
  get   'reset/:code' => 'password#edit',  as: :reset          # Password reset form
  patch 'reset/:code' => 'password#update'                     # Reset users password
  
  get 'vitaes'    => 'site#index'
  get 'vitae/:id' => 'site#index'
  
  # Dashboard
  root 'site#index'
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand logo" href="/">Civet</a>
    </div>
    <div class="tagline pull-right">résumés made easy</div>
  </div>
</header>

app/views/layouts/_messages.html.erb
<% flash.each do |name, message| %>
  <% if message.is_a?(String) || message.is_a?(ActiveModel::Errors) %>
  
    <% if message.is_a?(ActiveModel::Errors) %>
      <% msg = errors_to_ul(message) %>
    <% else %>
      <% msg = message %>
    <% end %>
    
    <% noty_type = (name == :notice ? "success" : "error") %>
    <% timeout = (name == :notice ? 4000 : 30000) %>
    
    <script>
      $(function() {
        noty({
          layout: 'bottomRight',
          type: "<%= noty_type %>",
          text: "<%= msg %>",
          timeout: "<%= timeout %>"
        });
      });
    </script>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<header class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand logo" href="#">Civet</a>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav pull-right">
        <li>
          <%= link_to "Sign out", logout_url, method: :delete, class: "logout-link" %>
        </li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <%= csrf_meta_tags %>
    
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <meta name="description" content="">
    <meta name="author" content="">
    
    <link rel="shortcut icon" href="/favicon.png">
    
    <title>civet ~ résumés made easy</title>

    <%= stylesheet_link_tag "application", media: "all" %>
    
    <%= include_gon %>
    
    <%= javascript_include_tag "application" %>
    
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    <div id="wrap">
      <% if current_user %>
        <%= render 'layouts/navigation' %>
      <% else %>
        <%= render 'layouts/header' %>
      <% end %>
      
      <div class="container">
        <%= yield %>
      </div>
    </div>

    <div id="footer">
      <div class="container">
        <p class="text-muted credit">&copy; 2013 by Civet</p>
      </div>
    </div>
    
    <%= render partial: 'layouts/messages' %>
  </body>
</html>